In [1]:
import pandas as pd
import random
import numpy as np
import glob
import os
import pickle

startDate = "20200427"
endDate = "20200428"
readPath = r'\\192.168.10.30\Kevin_zhenyu\rawData\***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i).split('_')[1] for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]
opath = []
tpath = []
for i in dataPathLs:
    opath.append(glob.glob(os.path.join(i, "mdOrderLog_***")))
    tpath.append(glob.glob(os.path.join(i, "mdTradeLog_***")))
opath1 = opath[::2]
opath2 = opath[1::2]
tpath1 = tpath[::2]
tpath2 = tpath[1::2]
print(opath1)
print(opath2)
print(tpath1)
print(tpath2)
F1 = open("\\\\192.168.10.30\\Kevin_zhenyu\\index\\weight_table_CSI1000.pkl", 'rb')
df1 = pickle.load(F1)


for i in range(len(opath1)):
    TradeLog = pd.read_csv(tpath2[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
    OrderLog = pd.read_csv(opath2[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
    TradeLog1 = pd.read_csv(tpath1[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
    OrderLog1 = pd.read_csv(opath1[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
    stocks = OrderLog1["SecurityID"].unique()
    
    d_ate = os.path.basename(tpath1[i][0]).split('_')[1]
    d_ate = d_ate[:4] + '-' + d_ate[4:6] + '-' + d_ate[6:]
    ID_list = df1[df1["date"] == d_ate]["ID"]
    len1 = ID_list[ID_list.str[:2] == "SH"].shape[0]
    len2 = ID_list[ID_list.str[:2] == "SZ"].shape[0]
    print(len1)
    print(len2)
    ID_list = ID_list.str[2:].astype(int)
    
    l1 = stocks[:1000]
    OrderLogSZ = OrderLog[OrderLog["SecurityID"].isin(l1)]
    OrderLogSZ1 = OrderLog1[OrderLog1["SecurityID"].isin(l1)]
    del OrderLog
    del OrderLog1
    OrderLogSZ["idx"] = np.where(OrderLogSZ["SecurityID"].isin(ID_list.values), 1, 0)
    OrderLogSZ1["idx"] = np.where(OrderLogSZ1["SecurityID"].isin(ID_list.values), 1, 0)
    print(len(OrderLogSZ["SecurityID"].unique()))
    print(len(OrderLogSZ1["SecurityID"].unique()))
    TradeLogSZ = TradeLog[TradeLog["SecurityID"].isin(l1)]
    TradeLogSZ1 = TradeLog1[TradeLog1["SecurityID"].isin(l1)]
    TradeLogSZ["idx"] = np.where(TradeLogSZ["SecurityID"].isin(ID_list.values), 1, 0)
    TradeLogSZ1["idx"] = np.where(TradeLogSZ1["SecurityID"].isin(ID_list.values), 1, 0)
    print(len(TradeLogSZ["SecurityID"].unique()))
    print(len(TradeLogSZ1["SecurityID"].unique()))
    del TradeLog
    del TradeLog1
    OrderLogSZ["OrderType"] = OrderLogSZ["OrderType"].apply(lambda x: str(x))
    OrderLogSZ1["OrderType"] = OrderLogSZ1["OrderType"].apply(lambda x: str(x))
    
    # TradeLog check
    TradeLogSZ["ExecType"] = TradeLogSZ["ExecType"].apply(lambda x: str(x))
    TradeLogSZ1["ExecType"] = TradeLogSZ1["ExecType"].apply(lambda x: str(x))
    columns = ["TransactTime","ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag","TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum","OfferApplSeqNum"]
    re = pd.merge(TradeLogSZ, TradeLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
    n1 = re["sequenceNo_x"].count()
    n2 = re["sequenceNo_y"].count()
    len1 = len(re)
    display(os.path.basename(os.path.basename(tpath2[i][0]).split("_")[1] + "_TradeLog Check_first 1000:"))
    print(n1)
    print(n2)
    print(len1)
    if len1 == n2:
            print((n2-n1)/n1)
    print((n1-n2)/n1)
    display(re[re["sequenceNo_y"].isnull()])
    display(re[re["sequenceNo_y"].isnull()]["SecurityID"].unique())
    display(re[re["sequenceNo_y"].isnull()]["TransactTime"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 1)])
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 1)]["SecurityID"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 1)]["TransactTime"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 0)])
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 0)]["SecurityID"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 0)]["TransactTime"].unique())
    
    display(re[re["sequenceNo_x"].isnull()])
    
    # OrderLog check    
    columns = ["TransactTime", "ApplSeqNum","Side",'OrderType', 'Price', 'OrderQty', "SecurityID"]
    ree = pd.merge(OrderLogSZ, OrderLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
    n1 = ree["sequenceNo_x"].count()
    n2 = ree["sequenceNo_y"].count()
    len1 = len(ree)
    display(os.path.basename(os.path.basename(tpath2[i][0]).split("_")[1] + "_OrderLog Check_first 1000:"))
    print(n1)
    print(n2)
    print(len1)
    if len1 == n2:
            print((n2-n1)/n1)
    print((n1-n2)/n1)
    display(ree[np.isnan(ree["sequenceNo_y"])])
    display(ree[ree["sequenceNo_y"].isnull()]["SecurityID"].unique())
    display(ree[ree["sequenceNo_y"].isnull()]["TransactTime"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 1)])
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 1)]["SecurityID"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 1)]["TransactTime"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 0)])
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 0)]["SecurityID"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 0)]["TransactTime"].unique())
    
    display(ree[np.isnan(ree["sequenceNo_x"])])

    
#     # among stocks ordering check
#     TradeLogSZ1["tradeseq"] = TradeLogSZ1.index.values
#     OrderLogSZ1["orderseq"] = OrderLogSZ1.index.values
#     SZ = pd.concat([TradeLogSZ, OrderLogSZ]).sort_values(by=["sequenceNo", "clockAtArrival"])
#     SZ1 = pd.concat([TradeLogSZ1, OrderLogSZ1]).sort_values(by=["sequenceNo", "clockAtArrival"])
#     del TradeLogSZ
#     del TradeLogSZ1
#     del OrderLogSZ
#     del OrderLogSZ1
#     print(len(SZ["SecurityID"].unique()))
#     print(len(SZ1["SecurityID"].unique()))
    
#     # within stocks ordering check
#     columns = ["TransactTime", "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag", "TradePrice", "TradeQty",
#            "TradeMoney", "BidApplSeqNum", "OfferApplSeqNum", "Side", "OrderType", "Price", "OrderQty"]
#     stocks = SZ["SecurityID"].unique()
#     m = 0
#     diff = []
#     for i1 in stocks:
#         re1 = pd.merge(SZ[SZ["SecurityID"] == i1], SZ1[SZ1["SecurityID"] == i1], left_on=columns, right_on=columns, how="inner")
#         if (sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]).any() == False:
#             m = m + 1
#         else:
#             diff.append(i1)
#     display(os.path.basename(os.path.basename(tpath2[i][0]).split("_")[1] + "_Ordering within stocks_first 1000:"))
#     if m == len(stocks):
#         print("SZE Trade + Order Data have same ordering within stocks")
#     print(m)
#     print(diff)
#     if len(diff)!=0:
#         for i1 in diff:
#             re1 = pd.merge(SZ[SZ["SecurityID"] == i1], SZ1[SZ1["SecurityID"] == i1], left_on=columns, right_on=columns, how="inner")
#             display(re1[sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]])
#     del re1
#     del SZ
#     del SZ1
    
            
            
    TradeLog = pd.read_csv(tpath2[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
    OrderLog = pd.read_csv(opath2[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
    TradeLog1 = pd.read_csv(tpath1[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag",
                                                 "TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum",
                                                 "OfferApplSeqNum"]]
    OrderLog1 = pd.read_csv(opath1[i][0], encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "exchId", "TransactTime",
                                                 "ApplSeqNum", "SecurityID", "Side", "OrderType", "Price",
                                                 "OrderQty"]]
    stocks = OrderLog1["SecurityID"].unique()
    l1 = stocks[1000:]
    OrderLogSZ = OrderLog[OrderLog["SecurityID"].isin(l1)]
    OrderLogSZ1 = OrderLog1[OrderLog1["SecurityID"].isin(l1)]
    OrderLogSZ["idx"] = np.where(OrderLogSZ["SecurityID"].isin(ID_list.values), 1, 0)
    OrderLogSZ1["idx"] = np.where(OrderLogSZ1["SecurityID"].isin(ID_list.values), 1, 0)
    print(len(OrderLogSZ["SecurityID"].unique()))
    print(len(OrderLogSZ1["SecurityID"].unique()))
    del OrderLog
    del OrderLog1
    TradeLogSZ = TradeLog[TradeLog["SecurityID"].isin(l1)]
    TradeLogSZ1 = TradeLog1[TradeLog1["SecurityID"].isin(l1)]
    TradeLogSZ["idx"] = np.where(TradeLogSZ["SecurityID"].isin(ID_list.values), 1, 0)
    TradeLogSZ1["idx"] = np.where(TradeLogSZ1["SecurityID"].isin(ID_list.values), 1, 0)
    print(len(TradeLogSZ["SecurityID"].unique()))
    print(len(TradeLogSZ1["SecurityID"].unique()))
    del TradeLog
    del TradeLog1
    OrderLogSZ["OrderType"] = OrderLogSZ["OrderType"].apply(lambda x: str(x))
    OrderLogSZ1["OrderType"] = OrderLogSZ1["OrderType"].apply(lambda x: str(x))
    
    # TradeLog check
    TradeLogSZ["ExecType"] = TradeLogSZ["ExecType"].apply(lambda x: str(x))
    TradeLogSZ1["ExecType"] = TradeLogSZ1["ExecType"].apply(lambda x: str(x))
    columns = ["TransactTime","ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag","TradePrice", "TradeQty", "TradeMoney", "BidApplSeqNum","OfferApplSeqNum"]
    re = pd.merge(TradeLogSZ, TradeLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
    n1 = re["sequenceNo_x"].count()
    n2 = re["sequenceNo_y"].count()
    len1 = len(re)
    display(os.path.basename(os.path.basename(tpath2[i][0]).split("_")[1] + "_TradeLog Check_second 1000:"))
    print(n1)
    print(n2)
    print(len1)
    if len1 == n2:
            print((n2-n1)/n1)
    print((n1-n2)/n1)
    display(re[re["sequenceNo_y"].isnull()])
    display(re[re["sequenceNo_y"].isnull()]["SecurityID"].unique())
    display(re[re["sequenceNo_y"].isnull()]["TransactTime"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 1)])
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 1)]["SecurityID"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 1)]["TransactTime"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 0)])
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 0)]["SecurityID"].unique())
    display(re[(re["sequenceNo_y"].isnull()) & (re["idx_x"] == 0)]["TransactTime"].unique())
    
    display(re[re["sequenceNo_x"].isnull()])
    
    # OrderLog check    
    columns = ["TransactTime", "ApplSeqNum","Side",'OrderType', 'Price', 'OrderQty', "SecurityID"]
    ree = pd.merge(OrderLogSZ, OrderLogSZ1, left_on=columns, right_on=columns, how="outer", validate='one_to_one')
    n1 = ree["sequenceNo_x"].count()
    n2 = ree["sequenceNo_y"].count()
    len1 = len(ree)
    display(os.path.basename(os.path.basename(tpath2[i][0]).split("_")[1] + "_OrderLog Check_second 1000:"))
    print(n1)
    print(n2)
    print(len1)
    if len1 == n2:
            print((n2-n1)/n1)
    print((n1-n2)/n1)
    display(ree[np.isnan(ree["sequenceNo_y"])])
    display(ree[ree["sequenceNo_y"].isnull()]["SecurityID"].unique())
    display(ree[ree["sequenceNo_y"].isnull()]["TransactTime"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 1)])
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 1)]["SecurityID"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 1)]["TransactTime"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 0)])
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 0)]["SecurityID"].unique())
    display(ree[(np.isnan(ree["sequenceNo_y"])) & (ree["idx_x"] == 0)]["TransactTime"].unique())
    
    display(ree[np.isnan(ree["sequenceNo_x"])])
    
#     # among stocks ordering check
#     TradeLogSZ1["tradeseq"] = TradeLogSZ1.index.values
#     OrderLogSZ1["orderseq"] = OrderLogSZ1.index.values
#     SZ = pd.concat([TradeLogSZ, OrderLogSZ]).sort_values(by=["sequenceNo", "clockAtArrival"])
#     SZ1 = pd.concat([TradeLogSZ1, OrderLogSZ1]).sort_values(by=["sequenceNo", "clockAtArrival"])
#     del TradeLogSZ
#     del TradeLogSZ1
#     del OrderLogSZ
#     del OrderLogSZ1
#     print(len(SZ["SecurityID"].unique()))
#     print(len(SZ1["SecurityID"].unique()))
    
#     # within stocks ordering check
#     columns = ["TransactTime", "ApplSeqNum", "SecurityID", "ExecType", "TradeBSFlag", "TradePrice", "TradeQty",
#            "TradeMoney", "BidApplSeqNum", "OfferApplSeqNum", "Side", "OrderType", "Price", "OrderQty"]
#     stocks = SZ["SecurityID"].unique()
#     m = 0
#     diff = []
#     for i1 in stocks:
#         re1 = pd.merge(SZ[SZ["SecurityID"] == i1], SZ1[SZ1["SecurityID"] == i1], left_on=columns, right_on=columns, how="inner")
#         if (sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]).any() == False:
#             m = m + 1
#         else:
#             diff.append(i1)
#     display(os.path.basename(os.path.basename(tpath2[i][0]).split("_")[1] + "_Ordering within stocks_second 1000:"))
#     if m == len(stocks):
#         print("SZE Trade + Order Data have same ordering within stocks")
#     print(m)
#     print(diff)
#     if len(diff)!=0:
#         for i1 in diff:
#             re1 = pd.merge(SZ[SZ["SecurityID"] == i1], SZ1[SZ1["SecurityID"] == i1], left_on=columns, right_on=columns, how="inner")
#             display(re1[sorted(re1["sequenceNo_y"]) != re1["sequenceNo_y"]])
#     del re1
#     del SZ
#     del SZ1

[['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200427_zs_92_01_day_data\\mdOrderLog_20200427_0832.csv'], ['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200428_zs_92_01_day_data\\mdOrderLog_20200428_0832.csv']]
[['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200427_zt_96_04_day_96data\\mdOrderLog_20200427_0835.csv'], ['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200428_zt_96_04_day_96data\\mdOrderLog_20200428_0846.csv']]
[['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200427_zs_92_01_day_data\\mdTradeLog_20200427_0832.csv'], ['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200428_zs_92_01_day_data\\mdTradeLog_20200428_0832.csv']]
[['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200427_zt_96_04_day_96data\\mdTradeLog_20200427_0835.csv'], ['\\\\192.168.10.30\\Kevin_zhenyu\\rawData\\logs_20200428_zt_96_04_day_96data\\mdTradeLog_20200428_0846.csv']]


C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\win\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


360
640
1000
1000


C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:68: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:69: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


1000
1000


'20200427_TradeLog Check_first 1000:'

19503083
19504730
19504730
8.444818698664206e-05
-8.444818698664206e-05


Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
19503083               NaN           NaN       NaN     102821480     7688996   
19503084               NaN           NaN       NaN     102821480     7482372   
19503085               NaN           NaN       NaN     102821480     7482374   
19503086               NaN           NaN       NaN     102821480     6894077   
19503087               NaN           NaN       NaN     102821480     7688998   
...                    ...           ...       ...           ...         ...   
19504725               NaN           NaN       NaN     102823140     7483922   
19504726               NaN           NaN       NaN     102823140     7483923   
19504727               NaN           NaN       NaN     102823140     7483924   
19504728               NaN           NaN       NaN     102823140     7483925   
19504729               NaN           NaN       NaN     102823140     7483926   

          SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
19503083         797        F           N       35200       900    31680000   
19503084        2030        4           N           0      2500           0   
19503085        2581        4           N           0       400           0   
19503086         876        4           N           0       700           0   
19503087        2925        F           N      491000       100    49100000   
...              ...      ...         ...         ...       ...         ...   
19504725        2179        F           N      349700       300   104910000   
19504726        2179        F           N      349700       400   139880000   
19504727        2179        F           N      349700       100    34970000   
19504728        2179        F           N      349700       100    34970000   
19504729        2179        F           N      349700       100    34970000   

          BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  \
19503083        7402769          7688995    NaN  1587954513468053   
19503084              0          7381385    NaN  1587954513468365   
19503085        7462805                0    NaN  1587954513470161   
19503086              0          6822816    NaN  1587954513470464   
19503087        7688997          7688987    NaN  1587954513471284   
...                 ...              ...    ...               ...   
19504725        7483914          7439440    NaN  1587954515131749   
19504726        7483914          7454827    NaN  1587954515131750   
19504727        7483914          7469566    NaN  1587954515131751   
19504728        7483914          7469919    NaN  1587954515131752   
19504729        7483914          7480840    NaN  1587954515131753   

          sequenceNo_y  exchId_y  idx_y  
19503083      43597599         2      1  
19503084      43597602         2      0  
19503085      43597605         2      1  
19503086      43597606         2      0  
19503087      43597608         2      0  
...                ...       ...    ...  
19504725      43608963         2      0  
19504726      43608964         2      0  
19504727      43608965         2      0  
19504728      43608966         2      0  
19504729      43608967         2      0  

[1647 rows x 18 columns]

'20200427_OrderLog Check_first 1000:'

21983799
21985823
21985823
9.206779956457935e-05
-9.206779956457935e-05


Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, Side, OrderType, Price, OrderQty, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, Side, OrderType, Price, OrderQty, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, Side, OrderType, Price, OrderQty, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
21983799               NaN           NaN       NaN     102821480     6894074   
21983800               NaN           NaN       NaN     102821480     7279138   
21983801               NaN           NaN       NaN     102821480     7482368   
21983802               NaN           NaN       NaN     102821480     6894075   
21983803               NaN           NaN       NaN     102821480     7688995   
...                    ...           ...       ...           ...         ...   
21985818               NaN           NaN       NaN     145959940    17370214   
21985819               NaN           NaN       NaN     145959940    15848329   
21985820               NaN           NaN       NaN     145959940    16463198   
21985821               NaN           NaN       NaN     145959940    15848330   
21985822               NaN           NaN       NaN     145959950    15848332   

          SecurityID  Side OrderType   Price  OrderQty  idx_x  \
21983799      300040     1         2   62900       300    NaN   
21983800      300144     1         2  263600       100    NaN   
21983801         519     2         2   96900     10000    NaN   
21983802      300160     1         2   59900       400    NaN   
21983803         797     2         2   35200       900    NaN   
...              ...   ...       ...     ...       ...    ...   
21985818      300801     2         2  208000      4900    NaN   
21985819        2258     2         2  150000       800    NaN   
21985820        2236     1         2  170500      2000    NaN   
21985821      300160     2         2   58900      2500    NaN   
21985822      300312     1         2   48200       100    NaN   

          clockAtArrival_y  sequenceNo_y  exchId_y  idx_y  
21983799  1587954513465674      43597589         2      0  
21983800  1587954513466056      43597593         2      0  
21983801  1587954513466662      43597594         2      0  
21983802  1587954513467206      43597597         2      0  
21983803  1587954513468049      43597598         2      1  
...                    ...           ...       ...    ...  
21985818  1587970811975314     108548108         2      0  
21985819  1587970811977703     108548113         2      1  
21985820  1587970811978872     108548115         2      0  
21985821  1587970811979077     108548116         2      0  
21985822  1587970811983205     108548119         2      0  

[2024 rows x 15 columns]

C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:187: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:188: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


1204
1204


C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:195: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\win\Anaconda3\lib\site-packages\ipykernel_launcher.py:196: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


1204
1204


'20200427_TradeLog Check_second 1000:'

11804127
11805160
11805160
8.75117660120058e-05
-8.75117660120058e-05


Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
11804127               NaN           NaN       NaN     102821470     7279134   
11804128               NaN           NaN       NaN     102821480     6894073   
11804129               NaN           NaN       NaN     102821480     7688994   
11804130               NaN           NaN       NaN     102821480     7279137   
11804131               NaN           NaN       NaN     102821480     7482370   
...                    ...           ...       ...           ...         ...   
11805155               NaN           NaN       NaN     102823140     7483910   
11805156               NaN           NaN       NaN     102823140     7483911   
11805157               NaN           NaN       NaN     102823140     7483912   
11805158               NaN           NaN       NaN     102823140     7483928   
11805159               NaN           NaN       NaN     102823140     7483929   

          SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
11804127      300701        4           N           0       700           0   
11804128        2878        4           N           0       100           0   
11804129      300254        4           N           0      1300           0   
11804130      300535        4           N           0      1000           0   
11804131      300386        F           N      170300       500    85150000   
...              ...      ...         ...         ...       ...         ...   
11805155      300316        F           N      202500       200    40500000   
11805156      300316        F           N      202500       100    20250000   
11805157      300316        F           N      202700       200    40540000   
11805158      300373        F           N      232100       400    92840000   
11805159      300373        F           N      232200       200    46440000   

          BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  \
11804127              0          7225463    NaN  1587954513461244   
11804128        6852544                0    NaN  1587954513463370   
11804129        7418522                0    NaN  1587954513465909   
11804130              0          6593375    NaN  1587954513466022   
11804131        7482369          7452535    NaN  1587954513466667   
...                 ...              ...    ...               ...   
11805155        7483907          7321363    NaN  1587954515126273   
11805156        7483907          7400356    NaN  1587954515126275   
11805157        7483907          7306329    NaN  1587954515126276   
11805158        7483927          7475261    NaN  1587954515131763   
11805159        7483927          7463018    NaN  1587954515131773   

          sequenceNo_y  exchId_y  idx_y  
11804127      43597584         2      0  
11804128      43597586         2      0  
11804129      43597590         2      0  
11804130      43597592         2      0  
11804131      43597596         2      1  
...                ...       ...    ...  
11805155      43608920         2      0  
11805156      43608921         2      0  
11805157      43608922         2      0  
11805158      43608969         2      1  
11805159      43608970         2      1  

[1033 rows x 18 columns]

'20200427_OrderLog Check_second 1000:'

13281696
13282842
13282842
8.628416129988219e-05
-8.628416129988219e-05


Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, Side, OrderType, Price, OrderQty, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, Side, OrderType, Price, OrderQty, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, Side, OrderType, Price, OrderQty, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

array([], dtype=int64)

array([], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
13281696               NaN           NaN       NaN     102821470     7482366   
13281697               NaN           NaN       NaN     102821480     7482367   
13281698               NaN           NaN       NaN     102821480     7279135   
13281699               NaN           NaN       NaN     102821480     7279136   
13281700               NaN           NaN       NaN     102821480     7482369   
...                    ...           ...       ...           ...         ...   
13282837               NaN           NaN       NaN     145959930    15848326   
13282838               NaN           NaN       NaN     145959940    15848328   
13282839               NaN           NaN       NaN     145959940    16724557   
13282840               NaN           NaN       NaN     145959940    15848331   
13282841               NaN           NaN       NaN     145959940    16724558   

          SecurityID  Side OrderType   Price  OrderQty  idx_x  \
13281696        2013     2         2   86000       500    NaN   
13281697        2239     2         2   36000       500    NaN   
13281698      300264     2         2   50600     20000    NaN   
13281699        2523     2         2   25800      5000    NaN   
13281700      300386     1         2  170300       500    NaN   
...              ...   ...       ...     ...       ...    ...   
13282837      300642     1         2  425900      5000    NaN   
13282838      300094     1         2   39800      3500    NaN   
13282839         952     1         2  109000       600    NaN   
13282840        2808     1         2   90400       100    NaN   
13282841      300142     2         2  417600       500    NaN   

          clockAtArrival_y  sequenceNo_y  exchId_y  idx_y  
13281696  1587954513462644      43597585         2      0  
13281697  1587954513464336      43597587         2      1  
13281698  1587954513465610      43597588         2      0  
13281699  1587954513466019      43597591         2      0  
13281700  1587954513466666      43597595         2      1  
...                    ...           ...       ...    ...  
13282837  1587970811969581     108548060         2      0  
13282838  1587970811974655     108548106         2      0  
13282839  1587970811977717     108548114         2      0  
13282840  1587970811979933     108548117         2      0  
13282841  1587970811982371     108548118         2      0  

[1146 rows x 15 columns]

360
640
1000
1000
1000
1000


'20200428_TradeLog Check_first 1000:'

24110892
24110605
24110892
1.190333397868482e-05


clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
379213  1588037410022975       3266839         2      93010260      565413   
379241  1588037410023593       3266993         2      93010270      529560   
379242  1588037410023595       3266994         2      93010270      529561   
379243  1588037410023740       3266995         2      93010270      529562   
379244  1588037410023742       3266996         2      93010270      529563   
...                  ...           ...       ...           ...         ...   
717355  1588037463763954       4849795         2      93104440      782635   
717356  1588037463763956       4849796         2      93104440      782636   
717357  1588037463764005       4849797         2      93104440      782637   
717358  1588037463764008       4849798         2      93104440      782638   
717359  1588037463764009       4849799         2      93104440      782639   

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
379213      300267        4           N           0       100           0   
379241        2415        F           N      312400       200    62480000   
379242        2415        F           N      312500       100    31250000   
379243        2415        F           N      312500       100    31250000   
379244        2415        F           N      312500       100    31250000   
...            ...      ...         ...         ...       ...         ...   
717355      300448        F           N       89900       100     8990000   
717356      300448        F           N       89900       100     8990000   
717357      300448        F           N       89900       100     8990000   
717358      300448        F           N       89900       100     8990000   
717359      300448        F           N       89900       500    44950000   

        BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  sequenceNo_y  \
379213              0           483618      0               NaN           NaN   
379241         529559           528238      0               NaN           NaN   
379242         529559           526904      0               NaN           NaN   
379243         529559           526938      0               NaN           NaN   
379244         529559           527644      0               NaN           NaN   
...               ...              ...    ...               ...           ...   
717355         782633           781267      0               NaN           NaN   
717356         782633           781298      0               NaN           NaN   
717357         782633           781386      0               NaN           NaN   
717358         782633           781391      0               NaN           NaN   
717359         782633           781414      0               NaN           NaN   

        exchId_y  idx_y  
379213       NaN    NaN  
379241       NaN    NaN  
379242       NaN    NaN  
379243       NaN    NaN  
379244       NaN    NaN  
...          ...    ...  
717355       NaN    NaN  
717356       NaN    NaN  
717357       NaN    NaN  
717358       NaN    NaN  
717359       NaN    NaN  

[287 rows x 18 columns]

array([300267,   2415,   2230,   2074,   2786,   2504,     19,   2239,
          156, 300058,     21,   2550,   2733,    975,    700,   2526,
          564,   2770,   2156, 300750,   2977, 300555,   2966,   2480,
            9,   2409,   2603,   2708,   2627, 300189,   2475,   2659,
       300328, 300783, 300297, 300416,   2810,    786, 300359, 300397,
           61, 300091,   2400,   2875,    425,    750,   2466,   2486,
         2353,   2401,   1979,   2765, 300192,   2405,   2812,     78,
         2183, 300075,   2928, 300661,   2628,   2488, 300332,   2124,
       300487, 300185, 300759,   2481,   2902, 300136,   2320,    917,
       300725,   2454,    625,   2650,   2300, 300569,    652,   2634,
       300002,   2631, 300394,    895, 300253,   2146,   2707,   2241,
       300178,   2487,   2354, 300448, 300828,   2630,   2262, 300133,
         2149,   2617, 300241, 300387, 300280,    665, 300072, 300583,
       300498, 300558, 300663,   2107,   2909,    999,   2426,    723,
      

array([93010260, 93010270, 93010280, 93010290, 93010300, 93010310,
       93010320, 93010330, 93010340, 93010350, 93010360, 93010370,
       93010380, 93010400, 93104280, 93104290, 93104300, 93104310,
       93104370, 93104380, 93104390, 93104400, 93104410, 93104420,
       93104430, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
379267  1588037410024252       3267124         2      93010270      565468   
379268  1588037410024376       3267167         2      93010270      565480   
379269  1588037410024377       3267168         2      93010270      565481   
379270  1588037410024380       3267170         2      93010270      565482   
379272  1588037410024498       3267187         2      93010270      565486   
...                  ...           ...       ...           ...         ...   
717131  1588037463734072       4848662         2      93104410      782396   
717132  1588037463734073       4848663         2      93104410      782397   
717133  1588037463734073       4848664         2      93104410      782398   
717134  1588037463734075       4848665         2      93104410      782399   
717351  1588037463763721       4849785         2      93104440      782630   

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
379267          19        4           N           0       800           0   
379268        2239        F           N       36900      1200    44280000   
379269        2239        F           N       36900      2500    92250000   
379270        2239        F           N       37000      1500    55500000   
379272          19        F           N      100300       100    10030000   
...            ...      ...         ...         ...       ...         ...   
717131      300726        4           N           0       100           0   
717132      300726        4           N           0       100           0   
717133      300726        4           N           0       100           0   
717134      300726        4           N           0       100           0   
717351      300558        F           N      980000       100    98000000   

        BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  sequenceNo_y  \
379267         246416                0      1               NaN           NaN   
379268         565479           561798      1               NaN           NaN   
379269         565479           562017      1               NaN           NaN   
379270         565479           561649      1               NaN           NaN   
379272         565485           561107      1               NaN           NaN   
...               ...              ...    ...               ...           ...   
717131              0           755793      1               NaN           NaN   
717132              0           755794      1               NaN           NaN   
717133              0           755796      1               NaN           NaN   
717134              0           755795      1               NaN           NaN   
717351         777426           782629      1               NaN           NaN   

        exchId_y  idx_y  
379267       NaN    NaN  
379268       NaN    NaN  
379269       NaN    NaN  
379270       NaN    NaN  
379272       NaN    NaN  
...          ...    ...  
717131       NaN    NaN  
717132       NaN    NaN  
717133       NaN    NaN  
717134       NaN    NaN  
717351       NaN    NaN  

[67 rows x 18 columns]

array([    19,   2239,   2550,   2733,   2156,   2409, 300328, 300783,
       300359, 300091,   2400,   2405, 300075,   2928, 300661,   2488,
       300332,   2124, 300487, 300185, 300759,   2481,   2320,    917,
       300725,   2650,    652,   2631, 300394, 300178,   2630,   2262,
         2617,    665, 300558,   2777,   2467,   2852, 300726],
      dtype=int64)

array([93010270, 93010280, 93010290, 93010300, 93010310, 93010320,
       93010340, 93010350, 93010360, 93010370, 93010400, 93104280,
       93104290, 93104300, 93104310, 93104370, 93104380, 93104390,
       93104400, 93104410, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
379213  1588037410022975       3266839         2      93010260      565413   
379241  1588037410023593       3266993         2      93010270      529560   
379242  1588037410023595       3266994         2      93010270      529561   
379243  1588037410023740       3266995         2      93010270      529562   
379244  1588037410023742       3266996         2      93010270      529563   
...                  ...           ...       ...           ...         ...   
717355  1588037463763954       4849795         2      93104440      782635   
717356  1588037463763956       4849796         2      93104440      782636   
717357  1588037463764005       4849797         2      93104440      782637   
717358  1588037463764008       4849798         2      93104440      782638   
717359  1588037463764009       4849799         2      93104440      782639   

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
379213      300267        4           N           0       100           0   
379241        2415        F           N      312400       200    62480000   
379242        2415        F           N      312500       100    31250000   
379243        2415        F           N      312500       100    31250000   
379244        2415        F           N      312500       100    31250000   
...            ...      ...         ...         ...       ...         ...   
717355      300448        F           N       89900       100     8990000   
717356      300448        F           N       89900       100     8990000   
717357      300448        F           N       89900       100     8990000   
717358      300448        F           N       89900       100     8990000   
717359      300448        F           N       89900       500    44950000   

        BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  sequenceNo_y  \
379213              0           483618      0               NaN           NaN   
379241         529559           528238      0               NaN           NaN   
379242         529559           526904      0               NaN           NaN   
379243         529559           526938      0               NaN           NaN   
379244         529559           527644      0               NaN           NaN   
...               ...              ...    ...               ...           ...   
717355         782633           781267      0               NaN           NaN   
717356         782633           781298      0               NaN           NaN   
717357         782633           781386      0               NaN           NaN   
717358         782633           781391      0               NaN           NaN   
717359         782633           781414      0               NaN           NaN   

        exchId_y  idx_y  
379213       NaN    NaN  
379241       NaN    NaN  
379242       NaN    NaN  
379243       NaN    NaN  
379244       NaN    NaN  
...          ...    ...  
717355       NaN    NaN  
717356       NaN    NaN  
717357       NaN    NaN  
717358       NaN    NaN  
717359       NaN    NaN  

[220 rows x 18 columns]

array([300267,   2415,   2230,   2074,   2786,   2504,    156, 300058,
           21,    975,    700,   2526,    564,   2770, 300750,   2977,
       300555,   2966,   2480,      9,   2603,   2708,   2627, 300189,
         2475,   2659, 300297, 300416,   2810,    786, 300397,     61,
         2875,    425,    750,   2466,   2486,   2353,   2401,   1979,
         2765, 300192,   2812,     78,   2183,   2628,   2902, 300136,
         2454,    625,   2300, 300569,   2634, 300002,    895, 300253,
         2146,   2707,   2241,   2487,   2354, 300448, 300828, 300133,
         2149, 300241, 300387, 300280, 300072, 300583, 300498, 300663,
         2107,   2909,    999,   2426,    723, 300115,   2174,    423,
         2483, 300234, 300547,   2223, 300132], dtype=int64)

array([93010260, 93010270, 93010280, 93010290, 93010300, 93010320,
       93010330, 93010340, 93010350, 93010360, 93010370, 93010380,
       93010400, 93104290, 93104300, 93104310, 93104370, 93104380,
       93104390, 93104400, 93104410, 93104420, 93104430, 93104440],
      dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

'20200428_OrderLog Check_first 1000:'

26817037
26816689
26817070
1.2976825142911949e-05


clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
257700       1.588037e+15      663748.0       2.0      91503690       99918   
257701       1.588037e+15      663751.0       2.0      91503690       95426   
257702       1.588037e+15      663752.0       2.0      91503690       95427   
257715       1.588037e+15      663775.0       2.0      91503690       95443   
257720       1.588037e+15      663782.0       2.0      91503690       95447   
...                   ...           ...       ...           ...         ...   
1552232      1.588037e+15     4849099.0       2.0      93104420      833963   
1552281      1.588037e+15     4849280.0       2.0      93104420      834002   
1552303      1.588037e+15     4849417.0       2.0      93104430      782556   
1552377      1.588037e+15     4849784.0       2.0      93104440      782629   
1552380      1.588037e+15     4849793.0       2.0      93104440      782633   

         SecurityID  Side OrderType   Price  OrderQty  idx_x  \
257700            2     2         2  261500       100    0.0   
257701       300443     2         2  182500       800    0.0   
257702          505     1         2   87800      1000    0.0   
257715            1     1         2  132100      2000    0.0   
257720         2584     2         2   81100       400    0.0   
...             ...   ...       ...     ...       ...    ...   
1552232        2466     1         2  170000       200    0.0   
1552281        2480     2         2   64100       100    0.0   
1552303      300732     1         2  168700       600    0.0   
1552377      300558     2         2  976300       100    1.0   
1552380      300448     1         2   89900      1000    0.0   

         clockAtArrival_y  sequenceNo_y  exchId_y  idx_y  
257700                NaN           NaN       NaN    NaN  
257701                NaN           NaN       NaN    NaN  
257702                NaN           NaN       NaN    NaN  
257715                NaN           NaN       NaN    NaN  
257720                NaN           NaN       NaN    NaN  
...                   ...           ...       ...    ...  
1552232               NaN           NaN       NaN    NaN  
1552281               NaN           NaN       NaN    NaN  
1552303               NaN           NaN       NaN    NaN  
1552377               NaN           NaN       NaN    NaN  
1552380               NaN           NaN       NaN    NaN  

[381 rows x 15 columns]

array([     2, 300443,    505,      1,   2584,    333,    768,     66,
         2916,   2619,   2202,   2195,   2503,   2936,   2370,    938,
         2385,   2256, 300146, 300142, 300207, 300189,   2230,   2405,
       300688, 300826,   2027, 300136,   2353,   2236,   2504,   2486,
         2756,     21,    917,   2631,     68, 300091,     19,   2467,
          564,   2030,   2239,   2480,   2104,    156, 300058,   2905,
          662,   2733,    975, 300234,    786, 300432,   2634,   2526,
       300267, 300287,    810,    731,   2351,   2156,   2770,    652,
       300555, 300828,   2977,   2966,    538,      9, 300192,   2466,
          488, 300409,    727,   1872,     61,   2627,   2451,    778,
         2022,   2475,   2436,    750,   2606,    963,   2165,    889,
       300077,   2603, 300827,   2812, 300706,   2718,   2124, 300416,
       300449,     46, 300213, 300002,   2400,   2426,   2135, 300003,
         2875,    425,     31,     36, 300115, 300397,   2264, 300498,
      

array([91503690, 93010260, 93010270, 93010280, 93010290, 93010300,
       93010310, 93010320, 93010330, 93010340, 93010350, 93010360,
       93010370, 93010380, 93010390, 93010400, 93104290, 93104300,
       93104310, 93104370, 93104380, 93104390, 93104400, 93104410,
       93104420, 93104430, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
257731       1.588037e+15      663804.0       2.0      91503690       95464   
257787       1.588037e+15      663919.0       2.0      91503690       99945   
257791       1.588037e+15      663923.0       2.0      91503690       99947   
1193764      1.588037e+15     3267001.0       2.0      93010270      529568   
1193777      1.588037e+15     3267050.0       2.0      93010270      565465   
...                   ...           ...       ...           ...         ...   
1552099      1.588037e+15     4848509.0       2.0      93104400      833822   
1552100      1.588037e+15     4848511.0       2.0      93104400      833824   
1552117      1.588037e+15     4848620.0       2.0      93104410      833842   
1552157      1.588037e+15     4848797.0       2.0      93104410      782438   
1552377      1.588037e+15     4849784.0       2.0      93104440      782629   

         SecurityID  Side OrderType    Price  OrderQty  idx_x  \
257731         2619     2         2    23900      2200    1.0   
257787         2370     2         2    64900     10000    1.0   
257791         2256     2         2    14300      5000    1.0   
1193764        2405     2         2   142700      2100    1.0   
1193777        2756     1         2   152100      1000    1.0   
...             ...   ...       ...      ...       ...    ...   
1552099        2467     1         2    67300      4200    1.0   
1552100      300091     1         2    34700     10000    1.0   
1552117      300613     1         2  1628000       100    1.0   
1552157          38     2         2   108300      1600    1.0   
1552377      300558     2         2   976300       100    1.0   

         clockAtArrival_y  sequenceNo_y  exchId_y  idx_y  
257731                NaN           NaN       NaN    NaN  
257787                NaN           NaN       NaN    NaN  
257791                NaN           NaN       NaN    NaN  
1193764               NaN           NaN       NaN    NaN  
1193777               NaN           NaN       NaN    NaN  
...                   ...           ...       ...    ...  
1552099               NaN           NaN       NaN    NaN  
1552100               NaN           NaN       NaN    NaN  
1552117               NaN           NaN       NaN    NaN  
1552157               NaN           NaN       NaN    NaN  
1552377               NaN           NaN       NaN    NaN  

[107 rows x 15 columns]

array([  2619,   2370,   2256,   2405,   2756,    917,   2631, 300091,
           19,   2467,   2239,   2104,    662,   2733, 300287,    810,
         2351,   2156,    652, 300409,   2451,   2022,   2436,    889,
         2124, 300213,   2400,   2135,     36, 300726, 300487, 300661,
       300332, 300185,   2928,   2100, 300725, 300759,   2481, 300194,
         2197, 300171,   2850, 300607,    688,   2664, 300366,   2531,
       300439, 300394, 300178,     16,   2630,   2262,   2429,    665,
       300558,   2488, 300101,   2777, 300613,     38], dtype=int64)

array([91503690, 93010270, 93010280, 93010290, 93010300, 93010320,
       93010340, 93010360, 93010370, 93010390, 93010400, 93104290,
       93104300, 93104310, 93104370, 93104380, 93104390, 93104400,
       93104410, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
257700       1.588037e+15      663748.0       2.0      91503690       99918   
257701       1.588037e+15      663751.0       2.0      91503690       95426   
257702       1.588037e+15      663752.0       2.0      91503690       95427   
257715       1.588037e+15      663775.0       2.0      91503690       95443   
257720       1.588037e+15      663782.0       2.0      91503690       95447   
...                   ...           ...       ...           ...         ...   
1552158      1.588037e+15     4848800.0       2.0      93104410      833894   
1552232      1.588037e+15     4849099.0       2.0      93104420      833963   
1552281      1.588037e+15     4849280.0       2.0      93104420      834002   
1552303      1.588037e+15     4849417.0       2.0      93104430      782556   
1552380      1.588037e+15     4849793.0       2.0      93104440      782633   

         SecurityID  Side OrderType   Price  OrderQty  idx_x  \
257700            2     2         2  261500       100    0.0   
257701       300443     2         2  182500       800    0.0   
257702          505     1         2   87800      1000    0.0   
257715            1     1         2  132100      2000    0.0   
257720         2584     2         2   81100       400    0.0   
...             ...   ...       ...     ...       ...    ...   
1552158        2205     1         2  126400       100    0.0   
1552232        2466     1         2  170000       200    0.0   
1552281        2480     2         2   64100       100    0.0   
1552303      300732     1         2  168700       600    0.0   
1552380      300448     1         2   89900      1000    0.0   

         clockAtArrival_y  sequenceNo_y  exchId_y  idx_y  
257700                NaN           NaN       NaN    NaN  
257701                NaN           NaN       NaN    NaN  
257702                NaN           NaN       NaN    NaN  
257715                NaN           NaN       NaN    NaN  
257720                NaN           NaN       NaN    NaN  
...                   ...           ...       ...    ...  
1552158               NaN           NaN       NaN    NaN  
1552232               NaN           NaN       NaN    NaN  
1552281               NaN           NaN       NaN    NaN  
1552303               NaN           NaN       NaN    NaN  
1552380               NaN           NaN       NaN    NaN  

[274 rows x 15 columns]

array([     2, 300443,    505,      1,   2584,    333,    768,     66,
         2916,   2202,   2195,   2503,   2936,    938,   2385, 300146,
       300142, 300207, 300189,   2230, 300688, 300826,   2027, 300136,
         2353,   2236,   2504,   2486,     21,     68,    564,   2030,
         2480,    156, 300058,   2905,    975, 300234,    786, 300432,
         2634,   2526, 300267,    731,   2770, 300555, 300828,   2977,
         2966,    538,      9, 300192,   2466,    488,    727,   1872,
           61,   2627,    778,   2475,    750,   2606,    963,   2165,
       300077,   2603, 300827,   2812, 300706,   2718, 300416, 300449,
           46, 300002,   2426, 300003,   2875,    425,     31, 300115,
       300397,   2264, 300498,   2401, 300387,   2765,     48,   2810,
          908,   2671, 300672,   2183,   2286,   2563,   2940,   2628,
         2607,   2329,    713, 300319, 300811,   2864, 300801, 300012,
          709,   2146,    686,    825,   2415,    401,    723,   2454,
      

array([91503690, 93010260, 93010270, 93010280, 93010290, 93010300,
       93010310, 93010320, 93010330, 93010340, 93010350, 93010360,
       93010370, 93010380, 93010400, 93104290, 93104300, 93104310,
       93104370, 93104380, 93104390, 93104400, 93104410, 93104420,
       93104430, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
26817037               NaN           NaN       NaN     145959900    21050452   
26817038               NaN           NaN       NaN     145959900    20010212   
26817039               NaN           NaN       NaN     145959900    18597736   
26817040               NaN           NaN       NaN     145959900    21050453   
26817041               NaN           NaN       NaN     145959900    20010214   
26817042               NaN           NaN       NaN     145959900    20010215   
26817043               NaN           NaN       NaN     145959910    20010216   
26817044               NaN           NaN       NaN     145959910    21050455   
26817045               NaN           NaN       NaN     145959910    20010219   
26817046               NaN           NaN       NaN     145959910    21050456   
26817047               NaN           NaN       NaN     145959920    20010220   
26817048               NaN           NaN       NaN     145959920    21050457   
26817049               NaN           NaN       NaN     145959930    20010222   
26817050               NaN           NaN       NaN     145959930    19552281   
26817051               NaN           NaN       NaN     145959930    20010223   
26817052               NaN           NaN       NaN     145959930    21050458   
26817053               NaN           NaN       NaN     145959930    19552282   
26817054               NaN           NaN       NaN     145959930    18597741   
26817055               NaN           NaN       NaN     145959930    21050459   
26817056               NaN           NaN       NaN     145959940    20010225   
26817057               NaN           NaN       NaN     145959940    19552283   
26817058               NaN           NaN       NaN     145959940    19552284   
26817059               NaN           NaN       NaN     145959940    18597742   
26817060               NaN           NaN       NaN     145959940    19552285   
26817061               NaN           NaN       NaN     145959940    20010226   
26817062               NaN           NaN       NaN     145959940    18597744   
26817063               NaN           NaN       NaN     145959940    21050461   
26817064               NaN           NaN       NaN     145959950    19552286   
26817065               NaN           NaN       NaN     145959950    21050462   
26817066               NaN           NaN       NaN     145959950    18597745   
26817067               NaN           NaN       NaN     145959960    19552287   
26817068               NaN           NaN       NaN     145959960    21050464   
26817069               NaN           NaN       NaN     145959960    19552288   

          SecurityID  Side OrderType   Price  OrderQty  idx_x  \
26817037        2370     1         2   61000       600    NaN   
26817038        2707     2         2   46300     20000    NaN   
26817039         573     2         2   25900      2100    NaN   
26817040         876     2         2  342500     20000    NaN   
26817041      300366     1         2   90100      2600    NaN   
26817042        2391     2         2   82700       300    NaN   
26817043        2239     1         2   35100       100    NaN   
26817044         936     2         2  101900     66300    NaN   
26817045        2480     2         2   64000     50000    NaN   
26817046         936     1         2  102000      2000    NaN   
26817047         564     2         2   32300      9000    NaN   
26817048          63     2         2  391400       300    NaN   
26817049        2237     1         2  137300      1000    NaN   
26817050         903     1         2   48500       500    NaN   
26817051        2426     1         2   23300      3400    NaN   
26817052      300217     1         2   24000     10000    NaN   
26817053         820     2         2    9400      3300    NaN   
26817054      300558     2         2  973300       500    NaN   
26817055        2888     2         2  187000       200

1196
1196
1196
1196


'20200428_TradeLog Check_second 1000:'

13374142
13373853
13374142
2.160886283396722e-05


clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
146729  1588037410022802       3266822         2      93010260      529532   
146730  1588037410022811       3266833         2      93010260      565411   
146745  1588037410023146       3266880         2      93010260      529549   
146773  1588037410023892       3267027         2      93010270      529575   
146774  1588037410023895       3267029         2      93010270      529577   
...                  ...           ...       ...           ...         ...   
320879  1588037463763728       4849790         2      93104440      834103   
320880  1588037463764014       4849800         2      93104440      782640   
320881  1588037463764015       4849801         2      93104440      782641   
320882  1588037463764121       4849803         2      93104440      782643   
320883  1588037463764123       4849804         2      93104440      782644   

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
146729      300286        4           N           0       100           0   
146730        2079        F           N       95300      4000   381200000   
146745      300761        4           N           0       100           0   
146773        2472        F           N       54000      1000    54000000   
146774      300055        F           N       57400       100     5740000   
...            ...      ...         ...         ...       ...         ...   
320879      300678        4           N           0      2500           0   
320880      300588        4           N           0      1000           0   
320881         929        4           N           0      2400           0   
320882      300588        4           N           0      1500           0   
320883      300588        4           N           0      2600           0   

        BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  sequenceNo_y  \
146729         529445                0      0               NaN           NaN   
146730         565410           356182      1               NaN           NaN   
146745         504264                0      1               NaN           NaN   
146773         529008           529574      0               NaN           NaN   
146774         529576           515457      1               NaN           NaN   
...               ...              ...    ...               ...           ...   
320879         831482                0      0               NaN           NaN   
320880              0           781826      0               NaN           NaN   
320881         229341                0      0               NaN           NaN   
320882              0           768253      0               NaN           NaN   
320883              0           768254      0               NaN           NaN   

        exchId_y  idx_y  
146729       NaN    NaN  
146730       NaN    NaN  
146745       NaN    NaN  
146773       NaN    NaN  
146774       NaN    NaN  
...          ...    ...  
320879       NaN    NaN  
320880       NaN    NaN  
320881       NaN    NaN  
320882       NaN    NaN  
320883       NaN    NaN  

[289 rows x 18 columns]

array([300286,   2079, 300761,   2472, 300055, 300623,   2428,   2087,
       300722,   2595,   2482,   2551,   2233,    608,   2755,   2066,
          965, 300391,   2163, 300315,   2052,   2676,   2702,   2791,
       300145,   2434, 300656,   2460, 300334,   2308, 300231,    721,
       300513,   2712, 300419,   2725, 300025, 300771,   2689, 300045,
          987, 300452, 300399, 300281, 300417, 300466, 300474, 300454,
         2923,   2890,   1696, 300489,   2911, 300462,    886,   2699,
       300491, 300289,   2534,   2899,      4,    880,    885, 300169,
         2666, 300193, 300532, 300210, 300147,   2396,   2816, 300584,
       300622, 300040,    627,   2078,     20, 300389, 300015,    498,
       300529,   2938, 300284,     32,   2453, 300459, 300068, 300211,
       300206, 300021,    526, 300735, 300096, 300566, 300582, 300567,
       300604, 300634,   2641,   2685, 300712, 300135, 300440,   2357,
         2878,   2698,   2585, 300481, 300038, 300031,   2838,   2788,
      

array([93010260, 93010270, 93010280, 93010290, 93010300, 93010310,
       93010320, 93010340, 93010350, 93010360, 93010370, 93010380,
       93010390, 93010400, 93010410, 93104290, 93104300, 93104310,
       93104370, 93104380, 93104390, 93104400, 93104410, 93104420,
       93104430, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
146730  1588037410022811       3266833         2      93010260      565411   
146745  1588037410023146       3266880         2      93010260      529549   
146774  1588037410023895       3267029         2      93010270      529577   
146775  1588037410023902       3267036         2      93010270      529580   
146776  1588037410023913       3267048         2      93010270      565463   
...                  ...           ...       ...           ...         ...   
320573  1588037463724362       4848086         2      93104390      833726   
320579  1588037463724554       4848126         2      93104390      782234   
320690  1588037463734127       4848667         2      93104410      782401   
320703  1588037463734682       4848720         2      93104410      833875   
320778  1588037463746649       4849179         2      93104420      782513   

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
146730        2079        F           N       95300      4000   381200000   
146745      300761        4           N           0       100           0   
146774      300055        F           N       57400       100     5740000   
146775      300623        F           N      336800       600   202080000   
146776        2428        4           N           0       400           0   
...            ...      ...         ...         ...       ...         ...   
320573      300474        4           N           0       300           0   
320579         885        F           N       91600       100     9160000   
320690        2216        F           N      219600      4500   988200000   
320703      300266        F           N       33000       100     3300000   
320778         885        F           N       91600       200    18320000   

        BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  sequenceNo_y  \
146730         565410           356182      1               NaN           NaN   
146745         504264                0      1               NaN           NaN   
146774         529576           515457      1               NaN           NaN   
146775         501915           529579      1               NaN           NaN   
146776              0           162333      1               NaN           NaN   
...               ...              ...    ...               ...           ...   
320573              0           831045      1               NaN           NaN   
320579         720584           782233      1               NaN           NaN   
320690         782400           781338      1               NaN           NaN   
320703         796333           833874      1               NaN           NaN   
320778         720584           782512      1               NaN           NaN   

        exchId_y  idx_y  
146730       NaN    NaN  
146745       NaN    NaN  
146774       NaN    NaN  
146775       NaN    NaN  
146776       NaN    NaN  
...          ...    ...  
320573       NaN    NaN  
320579       NaN    NaN  
320690       NaN    NaN  
320703       NaN    NaN  
320778       NaN    NaN  

[78 rows x 18 columns]

array([  2079, 300761, 300055, 300623,   2428,   2755,    965, 300145,
         2308,   2712, 300771, 300045, 300474,   1696,   2911,   2534,
          885,   2396,    498, 300284, 300068, 300021, 300735, 300096,
       300567, 300634,   2685,   2698,   2585, 300038, 300031, 300198,
       300630, 300662, 300624,   2705,   2216, 300266], dtype=int64)

array([93010260, 93010270, 93010290, 93010300, 93010310, 93010320,
       93010340, 93010350, 93010360, 93010370, 93010380, 93010400,
       93104300, 93104310, 93104370, 93104380, 93104390, 93104410,
       93104420], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
146729  1588037410022802       3266822         2      93010260      529532   
146773  1588037410023892       3267027         2      93010270      529575   
146777  1588037410023994       3267054         2      93010270      529584   
146780  1588037410024258       3267129         2      93010270      565471   
146781  1588037410024259       3267130         2      93010270      565472   
...                  ...           ...       ...           ...         ...   
320879  1588037463763728       4849790         2      93104440      834103   
320880  1588037463764014       4849800         2      93104440      782640   
320881  1588037463764015       4849801         2      93104440      782641   
320882  1588037463764121       4849803         2      93104440      782643   
320883  1588037463764123       4849804         2      93104440      782644   

        SecurityID ExecType TradeBSFlag  TradePrice  TradeQty  TradeMoney  \
146729      300286        4           N           0       100           0   
146773        2472        F           N       54000      1000    54000000   
146777        2087        4           N           0      4000           0   
146780      300722        F           N      204600       100    20460000   
146781      300722        F           N      204600       100    20460000   
...            ...      ...         ...         ...       ...         ...   
320879      300678        4           N           0      2500           0   
320880      300588        4           N           0      1000           0   
320881         929        4           N           0      2400           0   
320882      300588        4           N           0      1500           0   
320883      300588        4           N           0      2600           0   

        BidApplSeqNum  OfferApplSeqNum  idx_x  clockAtArrival_y  sequenceNo_y  \
146729         529445                0      0               NaN           NaN   
146773         529008           529574      0               NaN           NaN   
146777              0           517094      0               NaN           NaN   
146780         132377           565470      0               NaN           NaN   
146781         251393           565470      0               NaN           NaN   
...               ...              ...    ...               ...           ...   
320879         831482                0      0               NaN           NaN   
320880              0           781826      0               NaN           NaN   
320881         229341                0      0               NaN           NaN   
320882              0           768253      0               NaN           NaN   
320883              0           768254      0               NaN           NaN   

        exchId_y  idx_y  
146729       NaN    NaN  
146773       NaN    NaN  
146777       NaN    NaN  
146780       NaN    NaN  
146781       NaN    NaN  
...          ...    ...  
320879       NaN    NaN  
320880       NaN    NaN  
320881       NaN    NaN  
320882       NaN    NaN  
320883       NaN    NaN  

[211 rows x 18 columns]

array([300286,   2472,   2087, 300722,   2595,   2482,   2551,   2233,
          608,   2066, 300391,   2163, 300315,   2052,   2676,   2702,
         2791,   2434, 300656,   2460, 300334, 300231,    721, 300513,
       300419,   2725, 300025,   2689,    987, 300452, 300399, 300281,
       300417, 300466, 300454,   2923,   2890, 300489, 300462,    886,
         2699, 300491, 300289,   2899,      4,    880, 300169,   2666,
       300193, 300532, 300210, 300147,   2816, 300584, 300622, 300040,
          627,   2078,     20, 300389, 300015, 300529,   2938,     32,
         2453, 300459, 300211, 300206,    526, 300566, 300582, 300604,
         2641, 300712, 300135, 300440,   2357,   2878, 300481,   2838,
         2788, 300588, 300645, 300637, 300697, 300603,   2473, 300200,
       300258,   2014, 300460,   2125, 300655, 300687, 300683, 300586,
       300707, 300479,   2660, 300803,   2739, 300715, 300093,   2083,
       300585, 300692, 300730, 300667, 300681, 300678,    929],
      dtype=i

array([93010260, 93010270, 93010280, 93010290, 93010300, 93010310,
       93010320, 93010340, 93010350, 93010360, 93010370, 93010380,
       93010390, 93010400, 93010410, 93104290, 93104300, 93104310,
       93104370, 93104380, 93104390, 93104400, 93104410, 93104430,
       93104440], dtype=int64)

Empty DataFrame
Columns: [clockAtArrival_x, sequenceNo_x, exchId_x, TransactTime, ApplSeqNum, SecurityID, ExecType, TradeBSFlag, TradePrice, TradeQty, TradeMoney, BidApplSeqNum, OfferApplSeqNum, idx_x, clockAtArrival_y, sequenceNo_y, exchId_y, idx_y]
Index: []

'20200428_OrderLog Check_second 1000:'

14865299
14864951
14865316
2.341022538463572e-05


clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
118167      1.588037e+15      663790.0       2.0      91503690       95454   
118168      1.588037e+15      663791.0       2.0      91503690       95455   
118169      1.588037e+15      663792.0       2.0      91503690       95456   
118170      1.588037e+15      663793.0       2.0      91503690       95457   
118171      1.588037e+15      663795.0       2.0      91503690       99931   
...                  ...           ...       ...           ...         ...   
731490      1.588037e+15     4849615.0       2.0      93104430      834073   
731527      1.588037e+15     4849762.0       2.0      93104440      782624   
731528      1.588037e+15     4849767.0       2.0      93104440      782626   
731530      1.588037e+15     4849773.0       2.0      93104440      782627   
731532      1.588037e+15     4849802.0       2.0      93104440      782642   

        SecurityID  Side OrderType   Price  OrderQty  idx_x  clockAtArrival_y  \
118167      300431     1         2   20100       100    0.0               NaN   
118168        2780     2         2  190600       500    0.0               NaN   
118169        2780     2         2  193400       500    0.0               NaN   
118170        2365     2         2  116000      1000    0.0               NaN   
118171      300741     2         2  341800       500    1.0               NaN   
...            ...   ...       ...     ...       ...    ...               ...   
731490      300667     1         2  243900       200    0.0               NaN   
731527      300603     2         2  261700       100    0.0               NaN   
731528      300761     2         2  433900       100    1.0               NaN   
731530      300681     1         2  331800       100    0.0               NaN   
731532      300588     1         2   89100       800    0.0               NaN   

        sequenceNo_y  exchId_y  idx_y  
118167           NaN       NaN    NaN  
118168           NaN       NaN    NaN  
118169           NaN       NaN    NaN  
118170           NaN       NaN    NaN  
118171           NaN       NaN    NaN  
...              ...       ...    ...  
731490           NaN       NaN    NaN  
731527           NaN       NaN    NaN  
731528           NaN       NaN    NaN  
731530           NaN       NaN    NaN  
731532           NaN       NaN    NaN  

[365 rows x 15 columns]

array([300431,   2780,   2365, 300741,   2564, 300049,   2636, 300684,
         2737, 300633,   2760, 300223, 300229,   2079, 300263, 300119,
         2590,   2284,   2472, 300055,   2215, 300623, 300806,   2407,
       300575, 300813,   2623, 300722,   2595, 300086, 300285,   2482,
       300636, 300334,   2233, 300628, 300211, 300374,   2953,    987,
         2661,   2118,   2668,    965, 300567, 300198,   2316, 300535,
       300398, 300391, 300145,   2227, 300315, 300393, 300390,   2377,
         2308, 300231, 300419, 300326, 300215, 300513, 300025, 300001,
       300482,   2121, 300771, 300244,   2945,    735,   2689, 300204,
         2476, 300045, 300452,   2793,   2235, 300038, 300266, 300399,
       300130, 300474, 300466,   2771, 300454,   2890,   1696, 300770,
       300417,   2649, 300698,   2168, 300489,   2911, 300462,    886,
         2699, 300289,   2534, 300358,   2364,   2899,      4, 300604,
       300529, 300581,   2460, 300533,   2666, 300584,   2806, 300531,
      

array([91503690, 93010260, 93010270, 93010280, 93010290, 93010300,
       93010310, 93010320, 93010330, 93010340, 93010350, 93010360,
       93010370, 93010380, 93010400, 93010410, 93104280, 93104290,
       93104300, 93104310, 93104370, 93104380, 93104390, 93104400,
       93104410, 93104420, 93104430, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
118171      1.588037e+15      663795.0       2.0      91503690       99931   
118175      1.588037e+15      663801.0       2.0      91503690       99933   
118177      1.588037e+15      663805.0       2.0      91503690       95465   
118185      1.588037e+15      663817.0       2.0      91503690       95475   
118186      1.588037e+15      663818.0       2.0      91503690       95476   
...                  ...           ...       ...           ...         ...   
731298      1.588037e+15     4848798.0       2.0      93104410      782439   
731299      1.588037e+15     4848802.0       2.0      93104410      833896   
731373      1.588037e+15     4849153.0       2.0      93104420      782499   
731380      1.588037e+15     4849178.0       2.0      93104420      782512   
731528      1.588037e+15     4849767.0       2.0      93104440      782626   

        SecurityID  Side OrderType   Price  OrderQty  idx_x  clockAtArrival_y  \
118171      300741     2         2  341800       500    1.0               NaN   
118175        2564     1         2   43800      2000    1.0               NaN   
118177        2636     1         2   76600      2000    1.0               NaN   
118185      300684     1         2  276600       100    1.0               NaN   
118186        2737     1         2  133900       500    1.0               NaN   
...            ...   ...       ...     ...       ...    ...               ...   
731298      300623     1         2  335900       100    1.0               NaN   
731299         968     1         2   76000      1200    1.0               NaN   
731373      300393     2         2  136600       100    1.0               NaN   
731380         885     2         2   91600       200    1.0               NaN   
731528      300761     2         2  433900       100    1.0               NaN   

        sequenceNo_y  exchId_y  idx_y  
118171           NaN       NaN    NaN  
118175           NaN       NaN    NaN  
118177           NaN       NaN    NaN  
118185           NaN       NaN    NaN  
118186           NaN       NaN    NaN  
...              ...       ...    ...  
731298           NaN       NaN    NaN  
731299           NaN       NaN    NaN  
731373           NaN       NaN    NaN  
731380           NaN       NaN    NaN  
731528           NaN       NaN    NaN  

[109 rows x 15 columns]

array([300741,   2564,   2636, 300684,   2737, 300633, 300223, 300229,
         2079, 300263,   2590,   2284, 300055,   2215, 300623,   2668,
          965, 300567, 300198, 300398, 300145, 300393,   2377,   2308,
       300326, 300215, 300482,   2121, 300771,    735, 300045,   2235,
       300038, 300266, 300130, 300474,   1696, 300770,   2649,   2168,
         2911,   2534,   2364, 300533, 300531, 300238, 300039,   2396,
       300158,    498,    925, 300735, 300284, 300191, 300021, 300096,
       300634, 300424, 300232,    818,   2585, 300401, 300504, 300630,
         2705, 300388,    885,   2216,   2685,    968, 300761],
      dtype=int64)

array([91503690, 93010260, 93010270, 93010290, 93010300, 93010310,
       93010320, 93010330, 93010340, 93010350, 93010360, 93010370,
       93010380, 93010400, 93104280, 93104290, 93104300, 93104310,
       93104370, 93104380, 93104390, 93104410, 93104420, 93104440],
      dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
118167      1.588037e+15      663790.0       2.0      91503690       95454   
118168      1.588037e+15      663791.0       2.0      91503690       95455   
118169      1.588037e+15      663792.0       2.0      91503690       95456   
118170      1.588037e+15      663793.0       2.0      91503690       95457   
118176      1.588037e+15      663803.0       2.0      91503690       95463   
...                  ...           ...       ...           ...         ...   
731487      1.588037e+15     4849604.0       2.0      93104430      782597   
731490      1.588037e+15     4849615.0       2.0      93104430      834073   
731527      1.588037e+15     4849762.0       2.0      93104440      782624   
731530      1.588037e+15     4849773.0       2.0      93104440      782627   
731532      1.588037e+15     4849802.0       2.0      93104440      782642   

        SecurityID  Side OrderType   Price  OrderQty  idx_x  clockAtArrival_y  \
118167      300431     1         2   20100       100    0.0               NaN   
118168        2780     2         2  190600       500    0.0               NaN   
118169        2780     2         2  193400       500    0.0               NaN   
118170        2365     2         2  116000      1000    0.0               NaN   
118176      300049     2         2   85900       800    0.0               NaN   
...            ...   ...       ...     ...       ...    ...               ...   
731487      300730     2         2  131700       200    0.0               NaN   
731490      300667     1         2  243900       200    0.0               NaN   
731527      300603     2         2  261700       100    0.0               NaN   
731530      300681     1         2  331800       100    0.0               NaN   
731532      300588     1         2   89100       800    0.0               NaN   

        sequenceNo_y  exchId_y  idx_y  
118167           NaN       NaN    NaN  
118168           NaN       NaN    NaN  
118169           NaN       NaN    NaN  
118170           NaN       NaN    NaN  
118176           NaN       NaN    NaN  
...              ...       ...    ...  
731487           NaN       NaN    NaN  
731490           NaN       NaN    NaN  
731527           NaN       NaN    NaN  
731530           NaN       NaN    NaN  
731532           NaN       NaN    NaN  

[256 rows x 15 columns]

array([300431,   2780,   2365, 300049,   2760, 300119,   2472, 300806,
         2407, 300575, 300813,   2623, 300722,   2595, 300086, 300285,
         2482, 300636, 300334,   2233, 300628, 300211, 300374,   2953,
          987,   2661,   2118,   2316, 300535, 300391,   2227, 300315,
       300390, 300231, 300419, 300513, 300025, 300001, 300244,   2945,
         2689, 300204,   2476, 300452,   2793, 300399, 300466,   2771,
       300454,   2890, 300417, 300698, 300489, 300462,    886,   2699,
       300289, 300358,   2899,      4, 300604, 300529, 300581,   2460,
         2666, 300584,   2806,   2841, 300690, 300193, 300430, 300356,
          628, 300126, 300210, 300731, 300147,   2917, 300730, 300459,
       300040,   2831,    627, 300121,     20,   2311, 300470, 300389,
         2923, 300015,   2938, 300291,    518,     32, 300187,   2731,
       300206, 300810, 300479,    833, 300475, 300562, 300566, 300582,
         2829,   2641, 300655,    721, 300712,    880, 300135,   2702,
      

array([91503690, 93010260, 93010270, 93010280, 93010290, 93010300,
       93010310, 93010320, 93010340, 93010350, 93010360, 93010370,
       93010380, 93010400, 93010410, 93104290, 93104300, 93104310,
       93104370, 93104380, 93104390, 93104400, 93104410, 93104420,
       93104430, 93104440], dtype=int64)

clockAtArrival_x  sequenceNo_x  exchId_x  TransactTime  ApplSeqNum  \
14865299               NaN           NaN       NaN     145959900    20010211   
14865300               NaN           NaN       NaN     145959900    20010213   
14865301               NaN           NaN       NaN     145959900    19552279   
14865302               NaN           NaN       NaN     145959900    18597737   
14865303               NaN           NaN       NaN     145959910    21050454   
14865304               NaN           NaN       NaN     145959910    20010217   
14865305               NaN           NaN       NaN     145959910    20010218   
14865306               NaN           NaN       NaN     145959920    20010221   
14865307               NaN           NaN       NaN     145959920    18597738   
14865308               NaN           NaN       NaN     145959920    19552280   
14865309               NaN           NaN       NaN     145959920    18597739   
14865310               NaN           NaN       NaN     145959930    18597740   
14865311               NaN           NaN       NaN     145959930    20010224   
14865312               NaN           NaN       NaN     145959940    18597743   
14865313               NaN           NaN       NaN     145959940    21050460   
14865314               NaN           NaN       NaN     145959950    21050463   
14865315               NaN           NaN       NaN     145959960    19552289   

          SecurityID  Side OrderType    Price  OrderQty  idx_x  \
14865299        2307     2         2    56400       100    NaN   
14865300      300419     1         2    54000      2000    NaN   
14865301        2103     1         2    44100      1000    NaN   
14865302        2870     2         2   207400       200    NaN   
14865303      300404     2         2   229700       200    NaN   
14865304        2168     1         2    65600      1600    NaN   
14865305      300206     2         2   135500       200    NaN   
14865306      300106     1         2    63500      3000    NaN   
14865307      300169     2         2    61000       200    NaN   
14865308        2848     1         2   118600       400    NaN   
14865309        2768     1         2   381100      1000    NaN   
14865310      300694     1         2   116800      1700    NaN   
14865311        2551     2         2    75000     10000    NaN   
14865312        2623     2         2   301800      2400    NaN   
14865313        2327     2         2    72800       100    NaN   
14865314        2371     1         2  1419300       100    NaN   
14865315        2608     1         2    65000      4900    NaN   

          clockAtArrival_y  sequenceNo_y  exchId_y  idx_y  
14865299      1.588057e+15   125136246.0       2.0    1.0  
14865300      1.588057e+15   125136250.0       2.0    0.0  
14865301      1.588057e+15   125136253.0       2.0    0.0  
14865302      1.588057e+15   125136254.0       2.0    0.0  
14865303      1.588057e+15   125136257.0       2.0    0.0  
14865304      1.588057e+15   125136258.0       2.0    1.0  
14865305      1.588057e+15   125136260.0       2.0    0.0  
14865306      1.588057e+15   125136265.0       2.0    0.0  
14865307      1.588057e+15   125136266.0       2.0    0.0  
14865308      1.588057e+15   125136268.0       2.0    0.0  
14865309      1.588057e+15   125136269.0       2.0    1.0  
14865310      1.588057e+15   125136273.0       2.0    0.0  
14865311      1.588057e+15   125136277.0       2.0    0.0  
14865312      1.588057e+15   125136285.0       2.0    0.0  
14865313      1.588057e+15   125136287.0       2.0    1.0  
14865314      1.588057e+15   125136292.0       2.0    0.0  
14865315      1.588057e+15   125136296.0       2.0    0.0