In [1]:
import os
import glob
import pymongo
import numpy as np
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz

### 1. snapshot

In [3]:
logSZ1 = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200528\premdgw\mdL2Log_SZ.csv',
                    encoding="utf-8", nrows=1000000)
pd.set_option("max_columns", 200)
logSZ1[(logSZ1["ID"] == 2000533) & (logSZ1["time"] > 94000000)].head(10)

clockAtArrival  sequenceNo       ID      time  preClose   open  \
821328  1589852472000749539    12605445  2000533  94003000       287  28900   
823551  1589852475000717700    12644710  2000533  94006000       287  28900   
825783  1589852478000712511    12680477  2000533  94009000       287  28900   
828013  1589852481000714755    12717752  2000533  94012000       287  28900   
830211  1589852484000703586    12753949  2000533  94015000       287  28900   
832384  1589852487000703918    12789058  2000533  94018000       287  28900   
834555  1589852490000707311    12826295  2000533  94021000       287  28900   
836726  1589852493000706390    12863218  2000533  94024000       287  28900   
838908  1589852496000715575    12900854  2000533  94027000       287  28900   
841091  1589852499000716859    12939233  2000533  94030000       287  28900   

         high    low  close  cum_tradesCnt  cum_volume   cum_amount  vwapBid  \
821328  29200  28700  28800            524     1633900  47127400000        0   
823551  29200  28700  28700            527     1637900  47242200000        0   
825783  29200  28700  28700            527     1637900  47242200000        0   
828013  29200  28700  28700            531     1645900  47471800000        0   
830211  29200  28700  28700            531     1645900  47471800000        0   
832384  29200  28700  28700            531     1645900  47471800000        0   
834555  29200  28700  28800            532     1647200  47509240000        0   
836726  29200  28700  28800            533     1648700  47552440000        0   
838908  29200  28700  28800            533     1648700  47552440000        0   
841091  29200  28700  28800            533     1648700  47552440000        0   

        vwapAsk  totalBidQuantity  totalAskQuantity  bid1p  bid2p  bid3p  \
821328        0                 0                 0  28700  28600  28500   
823551        0                 0                 0  28700  28600  28500   
825783        0                 0                 0  28700  28600  28500   
828013        0                 0                 0  28700  28600  28500   
830211        0                 0                 0  28700  28600  28500   
832384        0                 0                 0  28700  28600  28500   
834555        0                 0                 0  28700  28600  28500   
836726        0                 0                 0  28700  28600  28500   
838908        0                 0                 0  28700  28600  28500   
841091        0                 0                 0  28700  28600  28500   

        bid4p  bid5p  bid6p  bid7p  bid8p  bid9p  bid10p  ask1p  ask2p  ask3p  \
821328  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
823551  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
825783  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
828013  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
830211  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
832384  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
834555  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
836726  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
838908  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   
841091  28400  28300  28200  28100  28000  27900   27800  28800  28900  29000   

        ask4p  ask5p  ask6p  ask7p  ask8p  ask9p  ask10p   bid1q   bid2q  \
821328  29100  29200  29300  29400  29500  29600   29700  140200  345600   
823551  29100  29200  29300  29400  29500  29600   29700  138200  345600   
825783  29100  29200  29300  29400  29500  29600   29700  138200  345600   
828013  29100  29200  29300  29400  29500  29600   29700  130200  347600   
830211  29100  29200  29300  29400  29500  29600   29700  130200  348600   
832384  29100  29200  29300  29400  29500  29600   29700  130200  348600   
8

In [4]:
display(logSZ1["vwapBid"].unique())
display(logSZ1["vwapAsk"].unique())
display(logSZ1["totalBidQuantity"].unique())
display(logSZ1["totalAskQuantity"].unique())

array([0], dtype=int64)

array([0], dtype=int64)

array([0], dtype=int64)

array([0], dtype=int64)

In [8]:
startTm = datetime.datetime.now()
logSZ = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\rawData\logs_20200528_zs_92_01_day_data\mdLog_SZ_20200528_0844.csv',
                    encoding="utf-8").loc[:, ["clockAtArrival", "sequenceNo", "source", "StockID",
                                              "exchange", "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "openPrice"]]
print(datetime.datetime.now() - startTm)

startTm = datetime.datetime.now()
logSZ1 = pd.read_csv(r'\\192.168.10.30\Kevin_zhenyu\check\20200528\premdgw\mdL2Log_SZ.csv',
                    encoding="utf-8")
display(logSZ1["vwapBid"].unique())
display(logSZ1["vwapAsk"].unique())
display(logSZ1["totalBidQuantity"].unique())
display(logSZ1["totalAskQuantity"].unique())




logSZ1 = logSZ1[["clockAtArrival", "sequenceNo", "ID",
                                              "time", "cum_volume", "cum_amount", "close",
                                              "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q",
                                              "bid2q", "bid3q", "bid4q", "bid5q", "ask1p", "ask2p",
                                              "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
                                              "ask4q", "ask5q", "open"]]
print(datetime.datetime.now() - startTm)

print("original data source type: ")
print(logSZ["source"].unique())
print(logSZ["time"].unique())
print(logSZ1["time"].unique())
logSZ["time"] = logSZ["time"].apply(lambda x: int((x.replace(':', "")).replace(".", "")))
logSZ1 = logSZ1.rename(columns={"open":"openPrice"})
logSZ1["StockID"] = logSZ1["ID"] - 2000000

array([0], dtype=int64)

array([0], dtype=int64)

array([0], dtype=int64)

array([0], dtype=int64)

0:03:55.441754
original data source type: 
[4 3]
[ 84454000  84457000  84554000 ... 151203000 151303000 151403000]
[ 90042000  90142000  90242000 ... 152330000 152333000 152336000]


AttributeError: 'int' object has no attribute 'replace'

In [13]:
pd.set_option("max_columns", 200)
display(logSZ[(logSZ["StockID"] == 1) & (logSZ["time"] >= 93000000) & (logSZ["source"] == 4)].head(10))
display(logSZ1[(logSZ1["StockID"] == 1) & (logSZ1["time"] >= 93000000)].head(10))

clockAtArrival  sequenceNo  source  StockID exchange      time  \
291572  1590629420735990     1900366       4        1       SZ  93000000   
294390  1590629423880938     2339748       4        1       SZ  93003000   
298800  1590629426839695     2698750       4        1       SZ  93006000   
303199  1590629429824902     2838138       4        1       SZ  93009000   
307571  1590629432803054     2927759       4        1       SZ  93012000   
311840  1590629435791931     3004839       4        1       SZ  93015000   
315937  1590629438782640     3081190       4        1       SZ  93018000   
320042  1590629441782102     3152998       4        1       SZ  93021000   
324066  1590629444780503     3226344       4        1       SZ  93024000   
328122  1590629447780543     3297042       4        1       SZ  93027000   

        cum_volume  cum_amount  close  bid1p  bid2p  bid3p  bid4p  bid5p  \
291572     1115200  14351514.0  12.83  12.82  12.81  12.80  12.79  12.78   
294390     1462300  18808449.0  12.86  12.85  12.83  12.82  12.81  12.80   
298800     1616900  20794478.0  12.85  12.84  12.83  12.82  12.81  12.80   
303199     1637700  21061803.0  12.86  12.85  12.84  12.83  12.82  12.81   
307571     1819500  23399515.0  12.85  12.85  12.84  12.83  12.82  12.81   
311840     2091278  26894859.3  12.85  12.86  12.85  12.84  12.83  12.82   
315937     2107678  27105747.3  12.85  12.85  12.84  12.83  12.82  12.81   
320042     2202178  28321748.3  12.86  12.85  12.84  12.83  12.82  12.81   
324066     2240678  28816956.3  12.86  12.85  12.84  12.83  12.82  12.81   
328122     2270078  29195267.3  12.87  12.86  12.85  12.84  12.83  12.82   

         bid1q   bid2q  bid3q  bid4q   bid5q  ask1p  ask2p  ask3p  ask4p  \
291572   21600   72000  91500   3700   53100  12.83  12.84  12.85  12.86   
294390   27600   13100  40500  33100  172400  12.86  12.87  12.88  12.89   
298800     300   11100  41600  36000  180500  12.85  12.86  12.87  12.88   
303199   25000     800   8800  41900   41600  12.86  12.87  12.88  12.89   
307571   31800    1300   8000  43100   41600  12.86  12.87  12.88  12.89   
311840     200   18622   3600   6800   43100  12.87  12.88  12.89  12.90   
315937  214922    3600   6700  43700   47200  12.87  12.88  12.89  12.90   
320042  239722    3600   6700  43200   47500  12.86  12.87  12.88  12.89   
324066  232022    3600   6500  43200   47500  12.87  12.88  12.89  12.90   
328122   13100  216922   3600   7000   48200  12.87  12.88  12.89  12.90   

        ask5p   ask1q   ask2q   ask3q   ask4q   ask5q  openPrice  
291572  12.87    4000    1900    4000   66900  311700      12.87  
294390  12.90  303578  396500   99050  181300  122700      12.87  
298800  12.89    2300  344778  402700   92650  162100      12.87  
303199  12.90  348678  401300   98850  102400  136400      12.87  
307571  12.90  198878  405000   98850  102400  137400      12.87  
311840  12.91  362300   98850  102400  137400  122600      12.87  
315937  12.91  355700   98850  101200  137400  122600      12.87  
320042  12.90    1100  276900   98650  101200  135400      12.87  
324066  12.91  257600   87650  101200  135400  122600      12.87  
328122  12.91  240900   87350  100600  135400  122600      12.87

clockAtArrival  sequenceNo       ID      time  cum_volume  \
303275  1589851869000596473     2121239  2000001  93000000     1496548   
310609  1589851872000739085     2565525  2000001  93003000     2566338   
313400  1589851875000700024     2982558  2000001  93006000     2798838   
316086  1589851878000685070     3249066  2000001  93009000     2943538   
318787  1589851881000689928     3336758  2000001  93012000     3058338   
321289  1589851884000663287     3402469  2000001  93015000     3262800   
323761  1589851887000665388     3455853  2000001  93018000     3378500   
326157  1589851890000663677     3510445  2000001  93021000     3640700   
328527  1589851893000653515     3567824  2000001  93024000     3704500   
330871  1589851896000652204     3625589  2000001  93027000     3718600   

          cum_amount   close   bid1p   bid2p   bid3p   bid4p   bid5p   bid1q  \
303275  200687646800  134200  134100  134000  133900  133800  133700  109152   
310609  344343556600  134100  134100  134000  133900  133800  133700  215962   
313400  375534186600  134200  134100  134000  133900  133800  133700  341162   
316086  394940936600  134200  134100  134000  133900  133800  133700  222662   
318787  410340496600  134200  134100  134000  133900  133800  133700  165962   
321289  437758380800  134100  134000  133900  133800  133700  133600  164400   
323761  453262670800  134000  134000  133900  133800  133700  133600   53600   
326157  488399300800  133800  133800  133700  133600  133500  133400   56400   
328527  496935960800  133800  133700  133600  133500  133400  133300   71300   
330871  498821800800  133700  133700  133600  133500  133400  133300   64000   

         bid2q   bid3q   bid4q   bid5q   ask1p   ask2p   ask3p   ask4p  \
303275  618100   49000   82500   83400  134200  134300  134400  134500   
310609  617600   58600   78200   72100  134300  134500  134600  134700   
313400  621300   58600   78200   72100  134200  134300  134400  134500   
316086  621600   58600   78600   72200  134200  134300  134400  134500   
318787  171600   59100   78600   72200  134200  134300  134400  134500   
321289   59100   78600   72200   55100  134100  134200  134300  134400   
323761   59100   79100   72200   55100  134100  134200  134300  134400   
326157   72200   55100  122300   84400  133900  134000  134100  134200   
328527   55100  122300   84400  196100  133800  133900  134000  134100   
330871   55300  122300   84400  196100  133800  133900  134000  134100   

         ask5p   ask1q   ask2q   ask3q   ask4q   ask5q  openPrice  StockID  
303275  134600   62600   45300   54900   55000   33200     134100        1  
310609  134800   19800   94292   81400  157700  180100     134100        1  
313400  134600   14500   16200   17500  251592  135300     134100        1  
316086  134600    3100  470300   20500  260292  141700     134100        1  
318787  134600   14000  494100   58500  269692  134700     134100        1  
321289  134500   60938   98300  485000   60000  271692     134100        1  
323761  134500  167338  234900  477600   66500  271692     134100        1  
326157  134300     900  225900   77838  280600  477600     134100        1  
328527  134200   28800   24000  249500   91738  270800     134100        1  
330871  134200   29000   25300  258100   92738  156100     134100        1

In [16]:
logSZ1[(logSZ1["StockID"] == 1)]["openPrice"].unique()

array([     0, 134100], dtype=int64)

In [17]:
datetime.datetime.fromtimestamp(1589852472000749539/1e9).strftime("%Y-%m-%d %H:%M:%S %f")

'2020-05-19 09:41:12 000750'

In [ ]:
data1 = logSZ[(logSZ["cum_volume"] > 0) & (logSZ["time"] < 145700000) & (logSZ["source"] == 4)]
del logSZ
data2 = logSZ1[(logSZ1["cum_volume"] > 0) & (logSZ1["time"] < 145700000)]
del logSZ1
columns = ["StockID", "cum_volume", "cum_amount", "close", "bid1p", "bid2p", "bid3p", "bid4p", "bid5p", "bid1q", "bid2q",
           "bid3q", "bid4q", "bid5q", "ask1p", "ask2p", "ask3p", "ask4p", "ask5p", "ask1q", "ask2q", "ask3q",
           "ask4q", "ask5q", "openPrice"]
data1_1["close"] = (data1_1["close"] * 10000).round(0)
data1_1["openPrice"] = (data1_1["openPrice"] * 10000).round(0)
data1_1["bid1p"] = (data1_1["bid1p"] * 10000).round(0)
data1_1["bid2p"] = (data1_1["bid2p"] * 10000).round(0)
data1_1["bid3p"] = (data1_1["bid3p"] * 10000).round(0)
data1_1["bid4p"] = (data1_1["bid4p"] * 10000).round(0)
data1_1["bid5p"] = (data1_1["bid5p"] * 10000).round(0)
data1_1["ask1p"] = (data1_1["ask1p"] * 10000).round(0)
data1_1["ask2p"] = (data1_1["ask2p"] * 10000).round(0)
data1_1["ask3p"] = (data1_1["ask3p"] * 10000).round(0)
data1_1["ask4p"] = (data1_1["ask4p"] * 10000).round(0)
data1_1["ask5p"] = (data1_1["ask5p"] * 10000).round(0)
data1_1["cum_amount"] = (data1_1["cum_amount"] * 10000).round(0)


data1_1 = data1.drop_duplicates(subset=columns, keep="first").reset_index()
data2_1 = data2.drop_duplicates(subset=columns, keep="first").reset_index()
n1 = len(data1_1["StockID"].unique())
n2 = len(data2_1["StockID"].unique())
print(n1)
print(n2)
if n1 != n2:
    sl = list(set(data1_1["StockID"].unique()) & (set(data2_1["StockID"].unique())))
    data1_1 = data1_1[data1_1["StockID"].isin(sl)]
    data2_1 = data2_1[data2_1["StockID"].isin(sl)]
test = pd.merge(data1_1, data2_1, left_on=columns, right_on=columns, how="outer")
n1 = test["time_x"].count()
n2 = test["time_y"].count()
len1 = len(test)
print(n1)
print(n2)
print(len1)
print("-----------------------------------------------")
if n2 < len1:
    display("test is not complete:")
    display(test[np.isnan(test["time_y"])])
    print(len(test[np.isnan(test["time_y"])])/n1)
if (len1 == n2) & (n1 < len1):
    display("baseline is not complete:")
    display(test[np.isnan(test["time_x"])])
    display(n2-n1)

### 2. trade data

### 3. order data